# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # SSH key importen
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]
  
  # Box Settings
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = 'webtest'

  # Provider Settings
  config.vm.provider "virtualbox" do |vb|
  vb.name = "webtest"
  end

  # Network Settings
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"


  # Folder Settings
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provision Settings
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end

end
